[sdl]
fullscreen=true
autolock=true
sensitivity=100
waitonerror=true

[dosbox]
memsize=64
machine=svga_s3

[render]
aspect=true
scaler=normal2x

[cpu]
core=auto
cputype=auto
cycles=auto

[autoexec]
@echo off
mount c /var/lib/retrowave/drives/c
c:
if exist AUTOEXEC.BAT call AUTOEXEC.BAT
