[sdl]
fullscreen=true
vsync=true

[dosbox]
memsize=64

[render]
aspect=true
integer_scaling=true

[cpu]
core=auto
cycles=max 105%

[autoexec]
@echo off
mount c /var/lib/retrowave/drives/c
c:
if exist AUTOEXEC.BAT call AUTOEXEC.BAT
